# Generated by Django 5.2 on 2025-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1 (Admin)'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4 (Writer)')], default=4),
        ),
    ]
