# Generated by Django 5.2 on 2025-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_level4text'),
    ]

    operations = [
        migrations.AddField(
            model_name='level4text',
            name='category',
            field=models.CharField(choices=[('highlight', 'Highlight'), ('lowlight', 'Lowlight')], default='Highlight', max_length=10),
        ),
    ]
