# Generated by Django 5.2 on 2025-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_level4text_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='div',
            field=models.CharField(choices=[('BE', 'Backend'), ('CSC', 'Corporate Supply Chain'), ('EWM', 'Enhanced Warehouse Management'), ('FE', 'Frontend'), ('PROC', 'Procurement'), ('QM', 'Quality Management'), ('ATV', 'Automotive'), ('CSS', 'Connected Secure Systems'), ('GIP', 'Green Industrial Power'), ('PSS', 'Power & Sensor Systems'), ('none', 'none')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_div',
            field=models.CharField(choices=[('FE VIH', 'Villach'), ('FE DRS', 'Dresden'), ('FE RBG', 'Regensburg'), ('FE KLM', 'Kulim'), ('FE QM', 'Quality Management'), ('FE T', 'T'), ('QM DI', 'DI'), ('QM PMT', 'PMT'), ('QM S', 'S'), ('QM SW', 'SW'), ('QM BE', 'Backend'), ('QM FE', 'Frontend'), ('QM GIP', 'Green Industrial Power'), ('QM JP', 'JP'), ('QM GC', 'GC'), ('QM AP', 'AP'), ('none', 'none')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1 (Admin)'), (2, 'Level 2 (DIV Manager)'), (3, 'Level 3 (SUB DIV Manager)'), (4, 'Level 4 (Writer)')], default=4),
        ),
    ]
