# Generated by Django 5.2 on 2025-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_div_alter_profile_sub_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='level4text',
            name='sub_div',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
