# Generated by Django 5.2 on 2025-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_div_alter_profile_sub_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='level4text',
            name='export_selected',
            field=models.BooleanField(default=True),
        ),
    ]
